from sqlalchemy import (
    BigInteger, Integer, SmallInteger, String, Text, TIMESTAMP, Identity,
    ForeignKeyConstraint, CheckConstraint, func,
)
from sqlalchemy.orm import Mapped, mapped_column, relationship
from datetime import datetime
from typing import Optional
from app.core.database import Base


class TimeEntryScreenshot(Base):
    """One screenshot captured by the desktop client during tracked time.

    The image itself lives in Google Drive; this row is its metadata and the
    only index into it. `file_path` holds the logical Drive path
    (``2026/September/User_101/2026-09-07/screenshot_<uuid>.webp``) for
    human troubleshooting, while `google_drive_file_id` is what the backend
    actually reads the bytes back with.

    `client_screenshot_id` is generated by the desktop before the upload and is
    UNIQUE: the client queues captures offline and retries with backoff, so a
    response lost after the file was already stored would otherwise produce a
    second Drive file and a duplicate row on the retry. The upload endpoint
    looks this key up first and returns the existing record instead.
    """

    __tablename__ = 'time_entry_screenshots'

    id: Mapped[int] = mapped_column(BigInteger, Identity(always=True), primary_key=True)
    organization_id: Mapped[int] = mapped_column(BigInteger, nullable=False)
    time_entry_id: Mapped[int] = mapped_column(BigInteger, nullable=False)
    captured_at: Mapped[datetime] = mapped_column(TIMESTAMP(timezone=True), nullable=False, server_default=func.now())
    file_path: Mapped[str] = mapped_column(Text, nullable=False)
    monitor_number: Mapped[int] = mapped_column(SmallInteger, nullable=False, default=1)

    #: Google Drive object identifiers. Null only while a row is in the
    #: transient `pending` state, which the current upload path never persists.
    google_drive_file_id: Mapped[Optional[str]] = mapped_column(String(255), nullable=True)
    google_drive_folder_id: Mapped[Optional[str]] = mapped_column(String(255), nullable=True)

    file_name: Mapped[Optional[str]] = mapped_column(String(255), nullable=True)
    file_size_bytes: Mapped[Optional[int]] = mapped_column(BigInteger, nullable=True)
    mime_type: Mapped[str] = mapped_column(String(100), nullable=False, default='image/webp', server_default='image/webp')

    width: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    height: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)

    #: 'uploaded' once the bytes are in Drive and this row is written;
    #: 'failed' if Drive rejected the object after the row existed.
    upload_status: Mapped[str] = mapped_column(String(20), nullable=False, default='uploaded', server_default='uploaded')
    uploaded_at: Mapped[Optional[datetime]] = mapped_column(TIMESTAMP(timezone=True), nullable=True)

    client_screenshot_id: Mapped[Optional[str]] = mapped_column(String(64), nullable=True)

    created_at: Mapped[datetime] = mapped_column(TIMESTAMP(timezone=True), nullable=False, server_default=func.now())

    __table_args__ = (
        ForeignKeyConstraint(['organization_id'], ['organizations.id'], name='time_entry_screenshots_organization_id_fkey', ondelete='CASCADE'),
        ForeignKeyConstraint(['time_entry_id'], ['time_entries.id'], name='time_entry_screenshots_time_entry_id_fkey', ondelete='CASCADE'),
        CheckConstraint(
            "upload_status IN ('pending', 'uploaded', 'failed')",
            name='time_entry_screenshots_upload_status_check',
        ),
    )

    # Relationships
    time_entry: Mapped["TimeEntry"] = relationship("TimeEntry")
