"""
notification_service — The single owner of notifications and the system tray.

Consolidates `ui/notification_manager.py`. Four audited problems are addressed:

**Notifications that never dismiss.** Every notification now has a deterministic
lifecycle owned by this service: it is shown, a single owned QTimer retires it,
and retirement also happens if the notification is superseded or the service
stops. A dismissal timer can no longer be orphaned by a widget being destroyed,
because no widget owns one.

**Notification storms.** Going offline and online repeatedly used to emit a
toast per transition, per subscriber. Notifications are now de-duplicated by
key within a cool-off window and rate-limited overall, so network flapping
produces one message rather than a burst.

**Unprofessional Windows identity.** Windows derives the name and icon shown on
a toast from the process's Application User Model ID. Without an explicit one,
it falls back to an autogenerated identifier (typically the interpreter), which
is what the screenshots showed. `SetCurrentProcessExplicitAppUserModelID` is
set here before any tray icon is created.

**Duplicate / lost tray icons.** The tray icon is created once, owned by this
service, and its availability is checked and logged rather than silently
assumed. If the platform has no tray, notifications degrade to logging instead
of disabling the application.
"""
from __future__ import annotations

import sys
import threading
import time
from typing import Dict, Optional

from PySide6.QtCore import QObject, QThread, QTimer, Qt, Signal
from PySide6.QtGui import QAction, QColor, QFont, QIcon, QPainter, QPixmap, QRadialGradient
from PySide6.QtWidgets import QMenu, QSystemTrayIcon

from core.service import BaseService

#: Stable identity for Windows toast attribution.
APP_USER_MODEL_ID = "Monitra"


class NotificationLevel:
    INFO = "info"
    SUCCESS = "success"
    WARNING = "warning"
    ERROR = "error"


_LEVEL_ICONS = {
    NotificationLevel.INFO: QSystemTrayIcon.MessageIcon.Information,
    NotificationLevel.SUCCESS: QSystemTrayIcon.MessageIcon.Information,
    NotificationLevel.WARNING: QSystemTrayIcon.MessageIcon.Warning,
    NotificationLevel.ERROR: QSystemTrayIcon.MessageIcon.Critical,
}


#: Base size the artwork is defined at. There is exactly one definition of
#: the mark (core/branding.py) and every size is rendered from it, so the
#: tray icon, the window icon, the .ico export and the sidebar can never
#: drift apart -- and dropping a real logo file into desktop/assets/
#: replaces all of them at once.
_ICON_BASE_SIZE = 64


def _paint_app_icon(size: int) -> QPixmap:
    """The Monitra mark at `size`, from the one shared definition.

    Falls back to the legacy hand-painted glyph only if rendering the mark
    somehow produces nothing, so a broken or missing asset can never leave
    the tray with no icon at all.
    """
    from core.branding import logo_pixmap

    pixmap = logo_pixmap(size)
    if not pixmap.isNull():
        return pixmap
    return _paint_legacy_app_icon(size)


def _paint_legacy_app_icon(size: int) -> QPixmap:
    from PySide6.QtGui import QLinearGradient, QPainterPath, QPen, QBrush

    pixmap = QPixmap(size, size)
    pixmap.fill(Qt.GlobalColor.transparent)

    painter = QPainter(pixmap)
    painter.setRenderHint(QPainter.RenderHint.Antialiasing)
    painter.scale(size / _ICON_BASE_SIZE, size / _ICON_BASE_SIZE)

    # 1. Linear Gradient: Cyan/Blue (#38BDF8 -> #3B82F6) to Purple (#8B5CF6)
    gradient = QLinearGradient(0, 0, 64, 64)
    gradient.setColorAt(0.0, QColor("#38BDF8"))
    gradient.setColorAt(0.4, QColor("#3B82F6"))
    gradient.setColorAt(1.0, QColor("#8B5CF6"))

    # 2. Outer Ring / Arc (Thick gradient stroke, open on right)
    pen_ring = QPen(QBrush(gradient), 6)
    pen_ring.setCapStyle(Qt.PenCapStyle.RoundCap)
    painter.setPen(pen_ring)
    painter.setBrush(Qt.BrushStyle.NoBrush)
    painter.drawArc(6, 6, 52, 52, -40 * 16, 340 * 16)

    # 3. Bold Centered Checkmark
    check_path = QPainterPath()
    check_path.moveTo(22, 32)
    check_path.lineTo(30, 41)
    check_path.lineTo(44, 23)

    pen_check = QPen(QBrush(gradient), 6)
    pen_check.setCapStyle(Qt.PenCapStyle.RoundCap)
    pen_check.setJoinStyle(Qt.PenJoinStyle.RoundJoin)
    painter.setPen(pen_check)
    painter.drawPath(check_path)

    painter.end()
    return pixmap


def create_app_icon(sizes: Optional[list] = None) -> QIcon:
    """Build the Monitra application icon from the shared brand mark. Pass `sizes` (e.g. for a build-time .ico export) to get a single
    QIcon carrying one crisp pixmap per size instead of one scaled-up
    bitmap; every existing caller keeps today's single-size behavior."""
    icon = QIcon()
    for size in (sizes or [_ICON_BASE_SIZE]):
        icon.addPixmap(_paint_app_icon(size))
    return icon


def set_windows_app_identity() -> None:
    """
    Declare an explicit Application User Model ID.

    Must run before the first tray icon is created. Without it, Windows
    attributes toasts to an autogenerated identifier rather than to Monitra.
    """
    if sys.platform != "win32":  # pragma: no cover - platform specific
        return
    try:
        import ctypes

        ctypes.windll.shell32.SetCurrentProcessExplicitAppUserModelID(APP_USER_MODEL_ID)
    except Exception:  # noqa: BLE001
        # Cosmetic only; never block startup for it.
        pass


class NotificationService(BaseService):
    """
    Owns notification delivery and the system tray icon.

    Signals:
        restore_requested() — user asked to bring the window back
        quit_requested()    — user asked to quit from the tray menu
    """

    name = "notifications"

    restore_requested = Signal()
    quit_requested = Signal()
    toast_requested = Signal(str, str, str)  # message, level, title

    #: A repeat of the same key inside this window is suppressed.
    DEDUPE_SECONDS = 2.0
    #: Ceiling on notifications shown per minute, whatever their key.
    MAX_PER_MINUTE = 30
    #: How long a toast is displayed before it is explicitly retired.
    DISPLAY_MS = 4000

    def __init__(self, runtime, parent: Optional[QObject] = None) -> None:
        super().__init__(runtime, parent)
        self._tray: Optional[QSystemTrayIcon] = None
        self._menu: Optional[QMenu] = None
        self._icon: Optional[QIcon] = None
        self._recent: Dict[str, float] = {}
        self._shown_times: list = []
        # Admission state is read and written by whichever thread calls
        # notify(); the tray itself is only ever touched on this object's own
        # thread (see `_deliver`).
        self._admit_lock = threading.Lock()
        # One owned timer retires the current toast. Single instance, single
        # owner: a dismissal timer can never be orphaned.
        self._dismiss_timer = QTimer(self)
        self._dismiss_timer.setSingleShot(True)
        self._dismiss_timer.timeout.connect(self._retire_current)
        self._available = False
        # A queued connection to self: whatever thread emits this signal, the
        # slot runs on the thread this service lives on (the GUI thread). It
        # is what makes notify() safe to call from anywhere -- see notify().
        self.toast_requested.connect(
            self._deliver, Qt.ConnectionType.QueuedConnection
        )

    # ── Lifecycle ─────────────────────────────────────────────────────────────

    def on_start(self) -> None:
        set_windows_app_identity()

        self._available = QSystemTrayIcon.isSystemTrayAvailable()
        if not self._available:
            # Not fatal. The audit found tray failures silently disabling
            # application behaviour; here it is logged and the app continues.
            self.log.warning(
                "no system tray available; notifications will be logged only"
            )
            return

        self._icon = create_app_icon()
        self._tray = QSystemTrayIcon(self._icon, self)
        self._tray.setToolTip("Monitra — Staff Management")
        self._tray.activated.connect(self._on_tray_activated)

        self._menu = QMenu()
        restore = QAction("Open Monitra", self)
        restore.triggered.connect(self.restore_requested.emit)
        self._menu.addAction(restore)
        self._menu.addSeparator()
        quit_action = QAction("Quit Monitra", self)
        quit_action.triggered.connect(self.quit_requested.emit)
        self._menu.addAction(quit_action)
        self._tray.setContextMenu(self._menu)

        self._tray.show()
        self.log.info("system tray initialised")

    def on_stop(self, timeout_ms: int) -> bool:
        self._dismiss_timer.stop()
        if self._tray is not None:
            self._tray.hide()
            self._tray.setContextMenu(None)
        if self._menu is not None:
            self._menu.deleteLater()
            self._menu = None
        self._tray = None
        return True

    @property
    def tray(self) -> Optional[QSystemTrayIcon]:
        """The tray icon, for callers that need to attach window behaviour."""
        return self._tray

    def _on_tray_activated(self, reason) -> None:
        if reason in (
            QSystemTrayIcon.ActivationReason.Trigger,
            QSystemTrayIcon.ActivationReason.DoubleClick,
        ):
            self.restore_requested.emit()

    # ── Delivery ──────────────────────────────────────────────────────────────

    def _admit(self, key: str) -> bool:
        """Apply de-duplication and rate limiting. True if the message may show."""
        now = time.monotonic()

        with self._admit_lock:
            last = self._recent.get(key)
            if last is not None and now - last < self.DEDUPE_SECONDS:
                self.log.debug("suppressed duplicate notification %r", key)
                return False

            self._shown_times = [t for t in self._shown_times if now - t < 60.0]
            if len(self._shown_times) >= self.MAX_PER_MINUTE:
                self.log.info("notification rate limit reached; suppressing %r", key)
                return False

            self._recent[key] = now
            self._shown_times.append(now)
            # Keep the dedupe map from growing without bound over a long session.
            if len(self._recent) > 64:
                cutoff = now - self.DEDUPE_SECONDS
                self._recent = {k: t for k, t in self._recent.items() if t >= cutoff}
        return True

    def _retire_current(self) -> None:
        """
        Explicitly end the current notification's lifecycle.

        The platform dismisses its own toast. This is the service's own
        end-of-life marker for it: the single owned timer that fires here is
        restarted, never accumulated, so no notification can outlive its
        display window without the service knowing.
        """
        self.log.debug("notification retired")

    def notify(
        self,
        message: str,
        level: str = NotificationLevel.INFO,
        title: str = "Monitra",
        key: Optional[str] = None,
    ) -> bool:
        """
        Show a notification.

        Safe to call from any thread. Admission control runs on the calling
        thread; the tray itself is only ever touched on the thread this
        service lives on, by hopping through a queued signal. Every caller
        today is already on the GUI thread, but nothing in the type system
        said so, and a single background service reaching in here directly
        would have been a widget mutated from a worker thread.

        :param key: De-duplication key; defaults to the message text. Callers
            that emit the same message for different reasons should pass a key
            so throttling behaves sensibly.
        :return: True if it was displayed, or handed to the GUI thread to
            display. False if it was suppressed or no tray exists.
        """
        dedupe_key = key or f"{level}:{message}"
        if not self._admit(dedupe_key):
            return False

        self.log.info("notify [%s] %s", level, message)

        if not self._available or self._tray is None:
            return False

        if QThread.currentThread() is not self.thread():
            self.toast_requested.emit(message, level, title)
            return True

        return self._deliver(message, level, title)

    def _deliver(self, message: str, level: str, title: str) -> bool:
        """Show an admitted notification. Runs on this service's own thread."""
        if not self._available or self._tray is None:
            return False

        try:
            # Use Monitra brand QIcon so Windows system toast displays Monitra logo
            tray_icon = self._icon if self._icon and not self._icon.isNull() else _LEVEL_ICONS.get(level, QSystemTrayIcon.MessageIcon.Information)
            self._tray.showMessage(
                title, message, tray_icon,
                self.DISPLAY_MS,
            )
        except Exception:  # noqa: BLE001
            self.log.exception("failed to display notification")
            return False

        self._dismiss_timer.start(self.DISPLAY_MS + 500)
        return True

    # ── Convenience wrappers (compatible with the previous manager) ───────────

    def show_info(self, message: str, title: str = "Monitra", key: Optional[str] = None) -> None:
        self.notify(message, NotificationLevel.INFO, title, key)

    def show_success(self, message: str, title: str = "Monitra", key: Optional[str] = None) -> None:
        self.notify(message, NotificationLevel.SUCCESS, title, key)

    def show_warning(self, message: str, title: str = "Monitra", key: Optional[str] = None) -> None:
        self.notify(message, NotificationLevel.WARNING, title, key)

    def show_error(self, message: str, title: str = "Monitra", key: Optional[str] = None) -> None:
        self.notify(message, NotificationLevel.ERROR, title, key)
